library/library/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views
app_name='books'
urlpatterns = [

    path('',views.home,name="home"),
    path('addbooks/',views.addbooks,name="addbooks"),
    path('viewbooks/',views.viewbooks,name="viewbooks"),
    path('factorial',views.factorial,name="factorial"),
    path('viewb<int:p>/',views.viewb,name="viewb"),
    path('deletebook<int:p>/',views.deletebook,name="deletebook"),
    path('editbook<int:p>/',views.editbook,name="editbook"),
]

library/library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('books.urls')),
    path('students',include('students.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

library/library/students/urls.py
from django.contrib import admin
from django.urls import path
from students import views
app_name="students"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register',views.register,name="register"),
    path('login',views.user_login,name="login"),
    path('logout',views.user_logout,name="logout"),
    path('studentdetails',views.studentdetails,name="studentdetails"),
    path('addstudents/',views.addstudents,name="addstudents"),
]

library/library/books/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    title=models.CharField(max_length=20)
    author=models.CharField(max_length=20)
    price=models.IntegerField()
    pdf=models.FileField(upload_to="book/pdf")
    image=models.ImageField(upload_to="book/cover",null=True,blank=True)


    def __str__(self):
        return self.title

library/library/students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name=models.CharField(max_length=20)
    age=models.IntegerField()
    place=models.CharField(max_length=20)

    def __str__(self):
        return self.name

library/library/books/forms.py
from django import forms
from books.models import Book


#form definition
class BookForm(forms.ModelForm):

    class Meta:

        model=Book

        fields="__all__"

library/library/books/views.py
from django.shortcuts import render
from books.models import Book
from books.forms import BookForm
from django.contrib.auth.decorators import login_required


# Create your views here.
def home(request):
    return render(request,'home.html')

@login_required
def addbooks(request):   #User defined
    if(request.method=="POST"):
        t=request.POST['t']
        a=request.POST['a']
        p=request.POST['p']
        f=request.FILES['f']
        i=request.FILES['i']
        b=Book.objects.create(title=t,author=a,price=p,pdf=f,image=i)
        b.save()
        return viewbooks(request)
    return render(request,'addbooks.html')

@login_required
def viewb(request,p):
    b=Book.objects.get(id=p)
    return render(request,'viewb.html',{'b':b})

@login_required
def deletebook(request,p):
    b=Book.objects.get(id=p)
    b.delete()
    return viewbooks(request)

#built-in

# def addbooks(request):
#     if(request.method=="POST"):
#         form=BookForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return viewbooks(request)
#
#     form=BookForm()      #empty form object
#     return render(request,"addbooks1.html",{'form':form})

@login_required
def viewbooks(request):
    b=Book.objects.all()
    return render(request,'viewbooks.html',{'book':b})

@login_required
def factorial(request):
    if(request.method=="POST"):
        n=int(request.POST['n'])
        fact=1
        for i in range(1,n+1):
            fact=fact*i
        return render(request,'fact.html',{'f':fact})

    return render(request,'fact.html')



@login_required
def editbook(request,p):
    b=Book.objects.get(id=p)
    if(request.method=="POST"):
        form=BookForm(request.POST,request.FILES,instance=b)
        if form.is_valid():
            form.save()
            return viewbooks(request)


    form=BookForm(instance=b)
    return render(request,'editbook.html',{'f':form})

library/library/students/views.py
from django.shortcuts import render,redirect
from students.models import Student
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here


def register(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p1=request.POST['p1']
        p2=request.POST['p2']
        e=request.POST['e']
        f=request.POST['f']
        l=request.POST['l']
        if(p1==p2):
            u=User.objects.create_user(username=u,password=p1,email=e,first_name=f,last_name=l)
            u.save()
            return redirect('books:home')

    return render(request,'register.html')
def user_login(request):
    if(request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p1']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('books:home')
        else:
            messages.error(request,"Invalid credentials")

    return render(request,'login.html')

@login_required
def user_logout(request):
    logout(request)
    return user_login(request)

@login_required
def studentdetails(request):
    b=Student.objects.all()
    return render(request,'studentdetails.html',{'details':b})

@login_required
def addstudents(request):
    if(request.method=="POST"):
        n=request.POST['n']
        a=request.POST['a']
        p=request.POST['p']
        b=Student.objects.create(name=n,age=a,place=p)
        b.save()
        return studentdetails(request)
    return render(request,"addstudents.html")

library/library/templates/addbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>You can add books here</h1>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Title:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter title" name="t">
</div><br><br>

    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Author:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter author" name="a">
</div><br><br>

    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Price:</label>
  <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="enter price" name="p">



    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Pdf:</label>
  <input type="file" class="form-control" id="exampleFormControlInput1" name="f">


         <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Cover image:</label>
  <input type="file" class="form-control" id="exampleFormControlInput1" name="i">
<br><br><br><br>

     <div class="mb-3">
         <input type="submit" class="form-control">
     </div>

</form>

{% endblock %}

library/library/templates/addbooks1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>You can add books here</h1>

<form method="POST">
  {% csrf_token %}
<table>
  {{form.as_table}}
</table>
  <input type="submit">
</form>
{% endblock %}

library/library/templates/addstudents.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>You can add students here</h1>


<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Name:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter the name" name="n">
</div><br><br>

    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Age:</label>
  <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="enter the age" name="a">
</div><br><br>

    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Place:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter the place" name="p">
</div><br><br><br>

     <div class="mb-3">
         <input type="submit" class="form-control">
     </div>

</form>

{% endblock %}

library/library/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container-fluid">
    <a class="navbar-brand text-warning" href="{% url 'books:home' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active text-warning" aria-current="page" href="{% url 'books:addbooks' %}">addbooks</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'books:viewbooks' %}">viewbooks</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'students:studentdetails' %}">Student Details</a>
        </li>

         <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'students:addstudents' %}">Add students</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'students:register' %}">register</a>
        </li>

        <li class="nav-item">
          <a class="nav-link text-warning"  href="{% url 'students:login' %}">login</a>
        </li>
        {%endif %}

        <li class="nav-item">
          <a class="nav-link text-warning" href="{% url 'books:factorial' %}">Factorial</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-warning"  href="{% url 'students:logout' %}">logout</a>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2 text-warning" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
</body>
</html>

library/library/templates/editbook.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Edit books here</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
<table>
{{f.as_table}}
    </table>
    <input type="submit">
    </form>
{% endblock %}

library/library/templates/fact.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>You can find the factorial here:</h1>

<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Number:</label>
  <input type="number" class="form-control" id="exampleFormControlInput1" placeholder="enter the number" name="n">
</div><br><br>


     <div class="mb-3">
         <input type="submit" class="form-control">
     </div>
    </form>
{% if f %}
<h2>The factorial is: {{f}}</h2>
{% endif %}

{% endblock %}

library/library/templates/home.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

{% if user.is_authenticated %}
<h1>Welcome To Home Page {{user.username}}</h1>
{% else %}
<p>Guest</p>
{% endif %}

{% endblock %}

library/library/templates/login.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>LOGIN</h1>

<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Username:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter username" name="u">
</div><br><br>

    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Password:</label>
  <input type="password" class="form-control" id="exampleFormControlInput1" placeholder="enter password" name="p1">
</div><br><br>

    <br><br>
    <div class="mb-3">
         <input type="submit" class="form-control">
     </div>

</form>

{% if messages %}
<ul>
    {% for msg in messages %}
    <li>{{msg}}</li>
    {% endfor %}
</ul>
{% endif %}

{% endblock %}

library/library/templates/register.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Registration</h1>


<form method="POST">
    {% csrf_token %}
<div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Username:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter username" name="u">
</div><br><br>

    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Password:</label>
  <input type="password" class="form-control" id="exampleFormControlInput1" placeholder="enter password" name="p1">
</div><br><br>

    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Confirm password:</label>
  <input type="password" class="form-control" id="exampleFormControlInput1" placeholder="enter password again" name="p2">
<br><br>


    <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Email:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter email id" name="e">
<br><br>

         <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">First name:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter first name" name="f">
             <br><br>


             <div class="mb-3">
  <label for="exampleFormControlInput1" class="form-label">Last name:</label>
  <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="enter last name" name="l">

<br><br>

     <div class="mb-3">
         <input type="submit" class="form-control">
     </div>

</form>

{% endblock %}

library/library/templates/studentdetails.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>View student Details</h1>
<table class="table table-bordered">
    <tr>
        <th>NAME</th>
        <th>AGE</th>
        <th>PLACE</th>
    </tr>

    {% for i in details %}
    <tr>
        <td>{{i.name}}</td>
        <td>{{i.age}}</td>
        <td>{{i.place}}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

library/library/templates/viewb.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>BOOK DETAILS</h1>
<center>
<table class="table table-bordered">

    <tr><th>COVER</th><td><img src="{{b.image.url}}"></td></tr>
    <tr><th>TITLE</th><td>{{b.title}}</td></tr>
    <tr><th>AUTHOR</th><td>{{b.author}}</td></tr>
    <tr><th>PRICE</th><td>{{b.price}}</td></tr>
    <tr><th>DOCUMENT</th><td><a href="{{b.pdf.url}}">download</a></td></tr>

</table>
    </center>
{% endblock %}

library/library/templates/viewbooks.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>You may view the books here</h1>

<table class="table table-bordered">
    <tr>
        <th>COVER</th>
        <th>TITLE</th>
        <th>AUTHOR</th>
        <th>PRICE</th>
        <th>DOCUMENT</th>
        <th>VIEW</th>
        <th>EDIT</th>
        <th>DELETE</th>
    </tr>
    {% for i in book %}
    <tr>
        <td><img src="{{i.image.url}}"></td>
        <td>{{i.title}}</td>
        <td>{{i.author}}</td>
        <td>{{i.price}}</td>
        <td><a href="{{i.pdf.url}}">DOWNLOAD</td>

        <td><a class="btn btn-warning" href="{% url 'books:viewb' i.id %}">View</a></td>
        <td><a class="btn btn-warning" href="{% url 'books:editbook' i.id %}">Edit</a></td>
        <td><a class="btn btn-warning" href="{% url 'books:deletebook' i.id %}">Delete</a></td>
    </tr>
    {% endfor %}
</table>

<!--<ol>-->
<!--    {% for i in book %}-->
<!--    <li>Books details</li>-->
<!--    <ul type="disc">-->
<!--    <li>Title-{{i.title}}</li>-->
<!--    <li>Author-{{i.author}}</li>-->
<!--    <li>Price-{{i.price}}</li>-->
<!--    </ul>-->
<!--    {% endfor %}-->
<!--</ol>-->
{% endblock %}